## **載入套件**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from keras import models
from keras import layers
from sklearn.neural_network import MLPRegressor

# **資料輸入**

In [81]:
#from google.colab import files
#uploaded=files.upload()

In [36]:
data=pd.read_csv('D:/workspace/usedcars/data/clean/practice.csv',header=0)
data.head()

horsepower  mileage    price
0         247       12  66903.0
1         296      254  84399.0
2         237      301  97579.0
3         320     6903  58995.0
4         201    30707  13324.0

# **資料編碼（標準化）**

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1395674 entries, 0 to 1395673
Data columns (total 3 columns):
 #   Column      Non-Null Count    Dtype  
---  ------      --------------    -----  
 0   horsepower  1395674 non-null  int64  
 1   mileage     1395674 non-null  int64  
 2   price       1395674 non-null  float64
dtypes: float64(1), int64(2)
memory usage: 31.9 MB


In [37]:
data=data.astype(np.float32)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1395674 entries, 0 to 1395673
Data columns (total 3 columns):
 #   Column      Non-Null Count    Dtype  
---  ------      --------------    -----  
 0   horsepower  1395674 non-null  float32
 1   mileage     1395674 non-null  float32
 2   price       1395674 non-null  float32
dtypes: float32(3)
memory usage: 16.0 MB


In [38]:
cols_to_norm = ['horsepower', 'mileage', 'price']
data[cols_to_norm] = data[cols_to_norm].apply(lambda x: (x - x.min()) / (x.max() - x.min())*0.6+0.2)

In [39]:
data.head()

horsepower   mileage     price
0    0.322449  0.200011  0.212518
1    0.355782  0.200241  0.215804
2    0.315646  0.200286  0.218279
3    0.372109  0.206555  0.211033
4    0.291156  0.229160  0.202456

# **擷取分析資料欄位**

In [40]:
y=data['price']

In [41]:
data =data.drop(['price','mileage'],axis=1)

# **分割資料：訓練與測試**

In [42]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, y,test_size=0.33, random_state=101)

In [43]:
X_train,y_train

(         horsepower
 221378     0.292517
 1187885    0.351701
 690205     0.310884
 856370     0.399320
 446657     0.282313
 ...             ...
 311895     0.325850
 661055     0.324490
 204614     0.250340
 1263115    0.338095
 1225567    0.263265
 
 [935101 rows x 1 columns],
 221378     0.204835
 1187885    0.202488
 690205     0.201249
 856370     0.203268
 446657     0.203099
              ...   
 311895     0.204855
 661055     0.206776
 204614     0.203802
 1263115    0.204084
 1225567    0.201921
 Name: price, Length: 935101, dtype: float32)

In [44]:
X_test,y_test

(         horsepower
 1123188    0.291156
 1337427    0.387075
 940159     0.321088
 710637     0.270068
 110040     0.423129
 ...             ...
 531284     0.440136
 554391     0.382313
 482037     0.270068
 689266     0.292517
 762291     0.372109
 
 [460573 rows x 1 columns],
 1123188    0.202393
 1337427    0.202769
 940159     0.203129
 710637     0.204550
 110040     0.206592
              ...   
 531284     0.209773
 554391     0.205169
 482037     0.203146
 689266     0.204459
 762291     0.202957
 Name: price, Length: 460573, dtype: float32)

In [92]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 935101 entries, 221378 to 1225567
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   horsepower  935101 non-null  float32
 1   mileage     935101 non-null  float32
dtypes: float32(2)
memory usage: 14.3 MB


# **SVR**

In [93]:
from sklearn import svm
svr = svm.SVR()

## **模式執行與評估**

In [94]:
svr.fit(X_train, y_train)
y_pred=svr.predict(X_train)

In [95]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from math import sqrt
import numpy as np

MSE = mean_squared_error(y_train, y_pred)
print('MSE=',MSE)
RMSE =np.sqrt(MSE)
print('RMSE=',RMSE)
MAE= mean_absolute_error(y_train, y_pred)
print('MAE=',MAE)

R2=1-MSE/np.var(y_train)
print("R2:", R2)

MSE= 0.00916140808784186
RMSE= 0.09571524480375036
MAE= 0.09567029808306698
R2: -889.1305131598555


## **測試結果**

In [96]:
y_pred=svr.predict(X_test)
y_pred

array([0.29982826, 0.30038404, 0.29975672, ..., 0.29963729, 0.29908939,
       0.30012557])

In [97]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from math import sqrt
import numpy as np

MSE = mean_squared_error(y_test, y_pred)
print('MSE=',MSE)
RMSE =np.sqrt(MSE)
print('RMSE=',RMSE)
MAE= mean_absolute_error(y_test, y_pred)
print('MAE=',MAE)

R2=1-MSE/np.var(y_test)
print("R2:", R2)


MSE= 0.009160093701656227
RMSE= 0.09570837842977085
MAE= 0.09566137466641805
R2: -861.206547197077


In [98]:
ytest = []
for value in y_test:
    ytest.append(value)
count=0
errvalue=abs((ytest-y_pred)/ytest)
errvalue

array([0.48141718, 0.48140708, 0.47569443, ..., 0.47498788, 0.46283076,
       0.47876266])

In [99]:
threshold=0.01  #門檻值
for i in range(len(errvalue)):
  if errvalue[i]<0.01:           
    count=count+1
print("通過門檻筆數",count)
print("通過門檻百分比",count/len(errvalue))

通過門檻筆數 2
通過門檻百分比 4.342416945847889e-06


# **Nearest Neighbors regression**

## **模式執行與評估**

In [45]:
from sklearn import neighbors
import numpy as np
n_neighbors = 5
for i, weights in enumerate(['uniform', 'distance']):
    knnr = neighbors.KNeighborsRegressor(n_neighbors, weights=weights)

In [46]:
knnr.fit(X_train, y_train)
y_pred=knnr.predict(X_train)

In [47]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from math import sqrt
import numpy as np

MSE = mean_squared_error(y_train, y_pred)
print('MSE=',MSE)
RMSE =np.sqrt(MSE)
print('RMSE=',RMSE)
MAE= mean_absolute_error(y_train, y_pred)
print('MAE=',MAE)

R2=1-MSE/np.var(y_train)
print("R2:", R2)

MSE= 4.565134063739589e-06
RMSE= 0.0021366174350453074
MAE= 0.0012418291293083477
R2: 0.5564475364662742


In [48]:
ytrain = []
for value in y_train:
    ytrain.append(value)
count=0
errvalue=abs((ytrain-y_pred)/ytrain)
errvalue

array([0.0024086 , 0.00492952, 0.00267461, ..., 0.00069261, 0.00539207,
       0.00179121])

In [49]:
threshold=0.02  #門檻值
for i in range(len(errvalue)):
  if errvalue[i]<0.02:           
    count=count+1
print("通過門檻筆數",count)
print("通過門檻百分比",count/len(errvalue))

通過門檻筆數 902212
通過門檻百分比 0.9648283982158077


## **測試結果**

In [50]:
y_pred=knnr.predict(X_test)
y_pred

array([0.20288241, 0.20378839, 0.20401545, ..., 0.20277667, 0.20434175,
       0.20398785])

In [51]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from math import sqrt
import numpy as np

MSE = mean_squared_error(y_test, y_pred)
print('MSE=',MSE)
RMSE =np.sqrt(MSE)
print('RMSE=',RMSE)
MAE= mean_absolute_error(y_test, y_pred)
print('MAE=',MAE)

R2=1-MSE/np.var(y_test)
print("R2:", R2)


MSE= 4.8461133228417965e-06
RMSE= 0.0022013889531025174
MAE= 0.0012479920124554087
R2: 0.5438528500360541


In [52]:
ytest = []
for value in y_test:
    ytest.append(value)
count=0
errvalue=abs((ytest-y_pred)/ytest)
errvalue

array([0.00241879, 0.00502531, 0.00436269, ..., 0.00181605, 0.00057504,
       0.00507801])

In [53]:
threshold=0.02  #門檻值
for i in range(len(errvalue)):
  if errvalue[i]<0.02:           
    count=count+1
print("通過門檻筆數",count)
print("通過門檻百分比",count/len(errvalue))

通過門檻筆數 443876
通過門檻百分比 0.9637473321275889


# **Bayesian Regression**

In [107]:
from sklearn import linear_model
from sklearn.linear_model import BayesianRidge, LinearRegression

bayr = linear_model.BayesianRidge()

## **模式執行與評估**

In [108]:
bayr.fit(X_train, y_train)
y_pred=bayr.predict(X_train)

In [109]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from math import sqrt
import numpy as np

MSE = mean_squared_error(y_train, y_pred)
print('MSE=',MSE)
RMSE =np.sqrt(MSE)
print('RMSE=',RMSE)
MAE= mean_absolute_error(y_train, y_pred)
print('MAE=',MAE)

R2=1-MSE/np.var(y_train)
print("R2:", R2)

MSE= 5.2255587e-06
RMSE= 0.002285948
MAE= 0.0010523704
R2: 0.49228012561798096


## **測試結果**

In [110]:
y_pred=knnr.predict(X_test)
y_pred

array([0.20226273, 0.20257483, 0.20329805, ..., 0.20366104, 0.20360649,
       0.20330239])

In [111]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from math import sqrt
import numpy as np

MSE = mean_squared_error(y_test, y_pred)
print('MSE=',MSE)
RMSE =np.sqrt(MSE)
print('RMSE=',RMSE)
MAE= mean_absolute_error(y_test, y_pred)
print('MAE=',MAE)

R2=1-MSE/np.var(y_test)
print("R2:", R2)


MSE= 3.6026948556815446e-06
RMSE= 0.0018980766200766355
MAE= 0.0007841980509252651
R2: 0.6608913409302554


In [112]:
ytest = []
for value in y_test:
    ytest.append(value)
count=0
errvalue=abs((ytest-y_pred)/ytest)
errvalue

array([0.00064296, 0.00095965, 0.00083096, ..., 0.00253732, 0.00417119,
       0.00170067])

In [113]:
threshold=0.01  #門檻值
for i in range(len(errvalue)):
  if errvalue[i]<0.01:           
    count=count+1
print("通過門檻筆數",count)
print("通過門檻百分比",count/len(errvalue))

通過門檻筆數 429051
通過門檻百分比 0.9315591665164914


# **Gaussian process regression (GPR).**

In [114]:
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import DotProduct, WhiteKernel

In [115]:
kernel = DotProduct() + WhiteKernel()
gpr = GaussianProcessRegressor(kernel=kernel,random_state=0)

## **模式執行與評估**

In [116]:
gpr.fit(X_train, y_train)
y_pred=gpr.predict(X_train)

MemoryError: Unable to allocate 3.18 TiB for an array with shape (935101, 935101) and data type float32

In [ ]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from math import sqrt
import numpy as np

MSE = mean_squared_error(y_train, y_pred)
print('MSE=',MSE)
RMSE =np.sqrt(MSE)
print('RMSE=',RMSE)
MAE= mean_absolute_error(y_train, y_pred)
print('MAE=',MAE)

R2=1-MSE/np.var(y_train)
print("R2:", R2)

MSE= 0.0033855296811270436
RMSE= 0.05818530468363162
MAE= 0.039989494844724915
R2: 0.7394646909452571


## **測試結果**

In [ ]:
y_pred=gpr.predict(X_test)
y_pred

array([0.65838419, 0.49823881, 0.35306502, 0.35830134, 0.54173553,
       0.55649978, 0.63912327, 0.24612883, 0.57707902, 0.23147309,
       0.53430205, 0.31391653, 0.35209673, 0.36699712, 0.46554889,
       0.40233447, 0.23230763, 0.56699553, 0.50923559, 0.46109578,
       0.29896866, 0.4077498 , 0.43180196, 0.46134433, 0.57696104,
       0.37894443, 0.55492753, 0.38143823, 0.48574387, 0.58727256,
       0.40136158, 0.37935635, 0.62045185, 0.7158749 , 0.53277302,
       0.42963231, 0.34470195, 0.37579415, 0.19301478, 0.54200059,
       0.45562652, 0.36214879, 0.58239304, 0.31783107, 0.36610982,
       0.46983538, 0.53412582, 0.34820168, 0.48973174, 0.44269562,
       0.55860249, 0.61333801, 0.44113607, 0.36512739, 0.53482023,
       0.1395299 , 0.40212548, 0.35606446, 0.43759904, 0.40577223,
       0.53289122, 0.18091743, 0.34579408, 0.40118323, 0.27237419,
       0.45282695, 0.45499982, 0.40099262, 0.36543801, 0.39493148,
       0.44882282, 0.41874047, 0.44071866, 0.39876413, 0.49842

In [ ]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from math import sqrt
import numpy as np

MSE = mean_squared_error(y_test, y_pred)
print('MSE=',MSE)
RMSE =np.sqrt(MSE)
print('RMSE=',RMSE)
MAE= mean_absolute_error(y_test, y_pred)
print('MAE=',MAE)

R2=1-MSE/np.var(y_test)
print("R2:", R2)


MSE= 0.005133644008946579
RMSE= 0.07164945225852448
MAE= 0.05073559878407546
R2: 0.7212031328698609


In [ ]:
ytest = []
for value in y_test:
    ytest.append(value)
count=0
errvalue=abs((ytest-y_pred)/ytest)
errvalue

array([1.77019770e-01, 1.91170751e-01, 2.20270753e-01, 7.92208331e-02,
       4.16268225e-03, 9.46316362e-02, 2.01095930e-01, 2.04324877e-01,
       1.56317240e-01, 6.15955994e-02, 1.96198569e-01, 1.04608900e-02,
       1.25587641e-01, 3.75950205e-02, 2.25128670e-01, 2.03823649e-01,
       1.45927895e-01, 1.04536781e-01, 5.39927820e-03, 4.47789118e-02,
       1.65505210e-02, 3.52922707e-02, 4.78773862e-01, 1.26241795e-01,
       8.51569155e-02, 4.94705150e-02, 6.71682482e-02, 2.17095381e-02,
       3.92820176e-01, 1.24340255e-02, 1.22387205e-01, 8.92641955e-03,
       1.38261360e-01, 1.05156394e-01, 1.82315393e-02, 1.15821766e-02,
       7.27238477e-02, 1.50390198e-01, 2.13254971e-01, 4.35283706e-02,
       3.73208705e-03, 1.12380391e-01, 1.88113768e-01, 1.08712938e-01,
       8.16643554e-02, 4.25341305e-02, 3.51274941e-02, 6.06070292e-02,
       8.34772386e-02, 2.27856544e-01, 9.52255987e-03, 4.42017302e-01,
       2.07489285e-01, 9.53821276e-02, 1.02650638e-01, 5.60304961e-01,
      

In [ ]:
threshold=0.02  #門檻值
for i in range(len(errvalue)):
  if errvalue[i]<0.02:           
    count=count+1
print("通過門檻筆數",count)
print("通過門檻百分比",count/len(errvalue))

通過門檻筆數 884760
通過門檻百分比 1.9209984085041893
